### ISSUE TITLE
Change the name?

### ISSUE THREAD

**Issue by messense** [PyO3/aiohttp-tokio#1]
`aiohttp-tokio` is a confusing name for `Asyncio event loop based on Tokio`, maybe drop the `http` part?

- aio-tokio
- async-tokio
- tokioloop/tokio-loop

**Comment by fafhrd91** [comment]
My idea for this package is to create custom RequestHandler for aiohttp, based on rust code (async-tokio/src/http)

**Comment by messense** [comment]
OK, I guess it should be clarified in `README.md`

**Comment by fafhrd91** [comment]
it is too early for decision. it is not clear how to distribute custom rust code.
